{% set name = "pdspy" %}
{% set version = "1.5.5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    path: ../pdspy

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv --no-deps"
    skip: True  # [win]

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
    host:
        - python
        - numpy >=1.16
        - cython
        - pip
    run:
        - python
        - {{ pin_compatible('numpy>=1.16') }}
        - scipy
        - matplotlib-base
        - astropy
        - h5py
        - mpi4py
        - emcee
        - dynesty
        - corner
        - galario
        - schwimmbad
        - scikit-learn

test:
    imports:
        - pdspy
    commands:
        - test -d ${PREFIX}
        - test -f ${PREFIX}/bin/disk_model.py

about:
    home: https://github.com/psheehan/pdspy
    license: GPL-3.0-only
    license_family: GPL
    license_file: LICENSE
    summary: 'Radiative transfer modeling of protoplanetary disks'

extra:
    recipe-maintainers:
        - psheehan
